DROP ROLE IF EXISTS ADMIN_DB;
CREATE ROLE ADMIN_DB;
GRANT CONNECT ON DATABASE crime_record_management_system TO ADMIN_DB;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE Criminal,courtHearing,jailLog,Jail,Cases,FIR,Officer,Suspect,Station,Users to ADMIN_DB;
-- GRANT ADMIN_DB to postgres;

DROP ROLE IF EXISTS JAILER;
CREATE ROLE JAILER;
GRANT CONNECT ON DATABASE crime_record_management_system TO JAILER;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE jailLog,Jail to JAILER;

DROP ROLE IF EXISTS PEOPLE;
CREATE ROLE PEOPLE;
GRANT CONNECT ON DATABASE crime_record_management_system TO PEOPLE;
GRANT SELECT ON TABLE FIR,Cases,courtHearing,Jail,Station to PEOPLE;

DROP ROLE IF EXISTS COURT;
CREATE ROLE COURT;
GRANT CONNECT ON DATABASE crime_record_management_system TO COURT;
GRANT SELECT ON TABLE courtHearing,Cases,Criminal,jailLog,Jail,Suspect,FIR,Station,Officer to COURT;
-- GRANT INSERT,UPDATE,DELETE on courtHearing,Cases,Criminal,jailLog,Jail to COURT;

DROP ROLE IF EXISTS POLICE;
CREATE ROLE POLICE;
GRANT CONNECT ON DATABASE crime_record_management_system TO POLICE;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE Station,FIR,Suspect,Officer to POLICE;