INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (2, 1, '2023-02-01', 'Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (2, 7, '2023-02-01', 'Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (3, 2, '2023-02-02', 'Not Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (3, 8, '2023-02-02', 'Not Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (5, 3, '2023-02-03', 'Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (5, 10, '2023-02-03', 'Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (6, 4, '2023-02-04', 'Not Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (8, 5, '2023-02-05', 'Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (8, 9, '2023-02-05', 'Guilty');
INSERT INTO courtHearing (case_id, suspect_id, dateofhearing, verdict) VALUES (9, 6, '2023-02-06', 'Not Guilty');