INSERT INTO Users VALUES ('Person1','ADMIN_DB');
INSERT INTO Users VALUES ('Person2','JAILER');
INSERT INTO Users VALUES ('Person3','PUBLIC');
INSERT INTO Users VALUES ('Person4','COURT');
INSERT INTO Users VALUES ('Person5','POLICE');